### ISSUE TITLE
Need to be able to set policy mode when creating new app function

### ISSUE THREAD

**Issue by Daniel-t** [jklotzsche-msft/PS.MTA-STS#13]
As per title.

TO facilitate multiple deployment stages the new-PSMTASTSFunctionAppDeployment script needs to accept a policy mode parameter.

**Comment by jklotzsche-msft** [comment]
issue solved by merging your recommendation. Thank you very much for contributing to this project!

**Comment by Daniel-t** [comment]
Not resolved, while the script now takes a PolicyMode parameter, it isn't used.  As this line has been commented out

https://github.com/jklotzsche-msft/PS.MTA-STS/blob/93d559fe85245214335bd4c3fbee027053d33c9a/PS.MTA-STS/functions/New-PSMTASTSFunctionAppDeployment.ps1#L215
